# -*- mode: conf; -*-

# home directoy
home = "~/.cpchain"

# for sample configuration, cf. https://github.com/toml-lang/toml/tree/master/examples
[chain]
contract_src_dir = "cpchain/assets/chain/contracts/Trading.sol"
contract_json = "cpchain/assets/chain/build/Trading.json"
registrar_json = "cpchain/assets/chain/registrar.json"
core_contract = "Trading"
# mode can be "test", "falcon", "local"
mode = "falcon"
ipc_provider_addr = "cpchain/assets/chain/sheds/data_dir/geth.ipc"
falcon_provider_addr = "http://192.168.0.132:8545"


[storage.s3]
bucket = "cpchain-bucket"
secret_access_key = "SECRET"
access_key_id = "SECRET"

[storage.ipfs]
addr = '192.168.0.132'
port = 5001

[wallet]
dbpath = "cpchain/assets/wallet/wallet.db"
download_dir = "~/.cpchain/downloads"
rsa_private_key_file = "cpchain/assets/wallet/private_key.pem"
rsa_private_key_password_file = 'cpchain/assets/wallet/password'
private_key_file = 'cpchain/assets/chain/sheds/data_dir/keystore/UTC--2018-01-25T08-04-38.217120006Z--22114f40ed222e83bbd88dc6cbb3b9a136299a23'
private_key_password_file = 'cpchain/assets/chain/sheds/password'

[wallet.qss]
main_window = "cpchain/assets/wallet/qss/main_window.qss"
sidebar = "cpchain/assets/wallet/qss/sidebar.qss"


[proxy]
server_host = 'localhost'
server_ctrl_port = 8000
server_data_port = 8001
server_key = 'cpchain/assets/proxy/key/server.key'
server_crt = 'cpchain/assets/proxy/key/server.crt'
dbpath = "cpchain/proxy/proxy.db"
server_root = 'cpchain/proxy/server_root'
default_ipfs_gateway = "192.168.0.132:5001"


[market]
server_addr = "192.168.0.132"
server_port = 8083
market_url = "http://192.168.0.132:8083/api/v1/"
default_password = "^-_-^cpchain@2018^-_-^"